server:
  port: 9090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: ms-auth
          uri: lb://ms-auth #lb = load balancer
          predicates:
            - Path=/ms-auth/**

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 30
  client:
    register-with-eureka: true
    service-url:
      default-zone: localhost:8761/eureka

logging:
  level:
    org.springframework: info
    it.cgmconsulting.gateway: info

# CUSTOM PROPERTIES
application:
  security:
    token: ${TOKEN}